### ISSUE TITLE
BUG: pilot.cfg always added as an argument with JobLaunchpad 

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/WebAppDIRAC#394] opened 2020-07-16 08:30 UTC
When launching jobs via JobLaunchpad the "pilot.cfg" string are always added to the arguments. That leads to errors similar to: 
```
/bin/sleep: invalid time interval ‘pilot.cfg’
Try '/bin/sleep --help' for more information.
```
This does not happen if jobs sent using DIRAC API.

**Comment by fstagni** [comment] 2020-07-16 14:20
As of nowadays, `pilot.cfg` should be removed.

**Comment by TaykYoku** [comment] 2021-07-22 22:54
I do not see references to pilot.cfg in the code of this project and I have not been able to reproduce such behavior. If this exception is still repeated, more information is needed to understand.

**Comment by fstagni** [comment] 2021-08-05 09:07
Is it still valid? @IgorPelevanyuk please answer, or we close this ticket.

**Comment by TaykYoku** [comment] 2021-08-19 09:29
I think it can be closed, because there is no new information about it.

**Closed as completed by TaykYoku** 2021-08-19 09:29 UTC
